15 communication with the server
Peralban/myteams pull request #24
Opened 2024-04-11 09:29 UTC by Quentintnrl

C'est normal que les fonctions d'écriture et de lecture du serveur soit vide.
@landryarki s'occude de cette partie. Son code sera lié au miens après sa pull request

2024-04-11 12:51 UTC, landryarki requested changes

2024-04-11 12:51 UTC, landryarki commented on src/client/check_command.c
> +    {"/info\n", 0, 0},
why putting \n at the end since command rarely come alone (with \n at the end)

2024-04-11 12:54 UTC, Peralban requested changes

2024-04-11 12:54 UTC, Peralban commented on tests/test_server.c
> +
Horrible :fire:

2024-04-11 13:24 UTC, Quentintnrl commented on src/client/check_command.c
> +    {"/info\n", 0, 0},
Because when i read it i need to keep its '\n'

2024-04-11 13:40 UTC, Peralban approved these changes

2024-04-12 17:56 UTC, Peralban approved these changes
One comment but its fine

2024-04-12 17:56 UTC, Peralban commented on src/client/init_client.c
> +    flags = fcntl(client->server_socket, F_GETFL, 0);
Do fcntl on the declaration of the var

2024-04-16 06:55 UTC, merged